---
- hosts: all
  become: true
  tasks:
    - name: Update system packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
        state: present
        update_cache: yes

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Enable Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    - name: Configure Grafana to listen on all interfaces
      lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: "^;http_addr"
        line: "http_addr = 0.0.0.0"
      notify: restart grafana

    - name: Ensure Grafana is running and enabled
      systemd:
        name: grafana-server
        state: started
        enabled: yes

  handlers:
    - name: restart grafana
      systemd:
        name: grafana-server
        state: restarted